import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f9f9fc',
        'surface-dim': '#dadadc',
        'surface-bright': '#f9f9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f6',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#5a403f',
        'inverse-surface': '#2f3133',
        'inverse-on-surface': '#f0f0f3',
        'outline': '#8e706e',
        'outline-variant': '#e2bebc',
        'surface-tint': '#b5252b',
        'primary': '#7d0011',
        'on-primary': '#ffffff',
        'primary-container': '#a31621',
        'on-primary-container': '#ffb2ae',
        'inverse-primary': '#ffb3ae',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3ae',
        'on-primary-fixed': '#410005',
        'on-primary-fixed-variant': '#920317',
        'secondary': '#545f6e',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e0f3',
        'on-secondary-container': '#586373',
        'secondary-fixed': '#d8e3f5',
        'secondary-fixed-dim': '#bcc7d9',
        'on-secondary-fixed': '#111c29',
        'on-secondary-fixed-variant': '#3d4856',
        'tertiary': '#383c3c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4f5353',
        'on-tertiary-container': '#c3c7c6',
        'tertiary-fixed': '#e0e3e2',
        'tertiary-fixed-dim': '#c4c7c6',
        'on-tertiary-fixed': '#181c1c',
        'on-tertiary-fixed-variant': '#434847',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f9f9fc',
        'on-background': '#1a1c1e',
        'surface-variant': '#e2e2e5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'container-max-width': '1280px',
        'unit': '4px',
      },
      fontFamily: {
        'hanken': ['Hanken Grotesk', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(0, 0, 0, 0.05)',
        'card-hover': '0px 8px 30px rgba(0, 0, 0, 0.08)',
        'top-bar': '0px -4px 16px rgba(0, 0, 0, 0.05)',
        'primary-glow': '0px 4px 20px rgba(125, 0, 17, 0.15)',
      },
      backgroundImage: {
        'dot-pattern': 'radial-gradient(#e2e2e5 1px, transparent 1px)',
      },
      backgroundSize: {
        'dot': '20px 20px',
      },
    },
  },
  plugins: [],
} satisfies Config
